-- SQL to create attendence_entry table for Supabase (Postgres)
CREATE TABLE public.attendence_entry (
  attendence_sl bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendence_date date NOT NULL,
  rfid_card_no text NOT NULL,
  attendence_time time WITHOUT TIME ZONE NULL
);

-- Run this in Supabase SQL editor (or via psql) to create the table.
